version: "3.7"
services:
  db:
    image: postgres:14
    container_name: db_auto_caption_system
    command:
      -p 1225
    expose:
      - 1225
    env_file:
      - .env_non-dev


  auto_caption_system:
    container_name: auto_caption_system
    build:
      context: .
    command: ["/auto_caption_system/docker/app.sh"]
    env_file:
      - .env_non-dev
    ports:
      - 4446:4446
    depends_on:
      - db